services:

  frontend:
    image: robert1730/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - strapi
    networks:
      - app-network

  strapi:
    image: robert1730/strapi:latest
    container_name: strapi
    expose:
      - "1337"
    restart: always
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge