FROM node:20-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG PUBLIC_ADMIN_URL=/strapi-admin
ENV PUBLIC_ADMIN_URL=${PUBLIC_ADMIN_URL}

RUN npm run build

EXPOSE 1337
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=1337

CMD ["npm", "run", "start"]